name: SplatoonSokuhou CheckUpdate

on:
  schedule:
    - cron: '5 22 * * *'
  workflow_dispatch:

jobs:
  build:
    env:
      CONSUMER_KEY: ${{ secrets.CK }}
      CONSUMER_SECRET: ${{ secrets.CS }}
      ACCESS_TOKEN: ${{ secrets.AT }}
      ACCESS_SECRET: ${{ secrets.AS }}
      SPSOKUHOU_DETA: ${{ secrets.SSD }}
      BSKY_ID: ${{ secrets.BSKYID }}
      BSKY_APPPASS: ${{ secrets.BSKYAPASS }}
    runs-on: ubuntu-latest
    name: SplatoonSokuhou Check Update
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install -r CheckUpdate-requirements.txt
      - name: Run Tweet Schedule
        run: |
          python3 CheckUpdate.py
