name: SplatoonSokuhou Tweet Schedule

on:
  schedule:
    - cron: '5 1 * * *'
    - cron: '5 3 * * *'
    - cron: '5 5 * * *'
    - cron: '5 7 * * *'
    - cron: '5 9 * * *'
    - cron: '5 11 * * *'
    - cron: '5 13 * * *'
    - cron: '5 15 * * *'
    - cron: '5 17 * * *'
    - cron: '5 19 * * *'
    - cron: '5 21 * * *'
    - cron: '5 23 * * *'
  workflow_dispatch:

jobs:
  build:
    env:
      CONSUMER_KEY: ${{ secrets.CK }}
      CONSUMER_SECRET: ${{ secrets.CS }}
      ACCESS_TOKEN: ${{ secrets.AT }}
      ACCESS_SECRET: ${{ secrets.AS }}
      SPSOKUHOU_DETA: ${{ secrets.SSD }}
    runs-on: ubuntu-latest
    name: SplatoonSokuhou Tweet Schedule
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install -r Schedule-requirements.txt
      - name: Run Tweet Schedule
        run: |
          python3 WaitAndTweetSchedule.py
