name: SplatoonSokuhou Tweet GesoTown Pickup

on:
  schedule:
    - cron: '20 23 * * *'
  workflow_dispatch:

jobs:
  build:
    env:
      CONSUMER_KEY: ${{ secrets.CK }}
      CONSUMER_SECRET: ${{ secrets.CS }}
      ACCESS_TOKEN: ${{ secrets.AT }}
      ACCESS_SECRET: ${{ secrets.AS }}
      SPSOKUHOU_DETA: ${{ secrets.SSD }}
    runs-on: ubuntu-latest
    name: SplatoonSokuhou Tweet GesoTown Pickup
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install -r Schedule-requirements.txt
      - name: Run Tweet GesoTown Pickup
        run: |
          python3 GesoTownUpdatePickup.py