name: SplatoonSokuhou Tweet NewGear

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    env:
      CONSUMER_KEY: ${{ secrets.CK }}
      CONSUMER_SECRET: ${{ secrets.CS }}
      ACCESS_TOKEN: ${{ secrets.AT }}
      ACCESS_SECRET: ${{ secrets.AS }}
    runs-on: ubuntu-latest
    name: SplatoonSokuhou Tweet NewGear
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install -r Schedule-requirements.txt
      - name: Run Tweet Schedule
        run: |
          python3 SplatoonNewGear.py